---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-projects
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-projects
  template:
    metadata:
      labels:
        app: static-projects
    spec:
      containers:
        - name: nginx
          image: localhost:5000/wetransform/static-projects:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: static-projects
spec:
  selector:
    app: static-projects
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP